<a href="https://colab.research.google.com/github/anchal-rai/ml/blob/main/AnchalRai(2201330100301)BreastCancerDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PROJECT  TITLE : Breast Cancer Classification
Breast cancer classification using ml algorithm :
Decision tree, random forest, svm and naive byes

**IMPORTING NEEDED LIBRARIES**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score


1. Loading the data
2. Dropping the unnecessary columns
2. Dividing the datset into testing and training data


In [ ]:
df=pd.read_csv('BreastCancer.csv')
print(df.head())

# ENcode the target variable : Maligant as 1 and Benign B as

df['diagnosis']=df['diagnosis'].map({'M':1,'B':0})
# Select features and target
# print(df.head())

# Select features and target

X=df.drop(columns=['id','diagnosis','Unnamed: 32'],axis=1)
y=df['diagnosis']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=101)

# Scale the feature data

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness

# DECISION TREE

In [ ]:
from sklearn.tree import DecisionTreeClassifier
# Initialize and train the Decisionn Tree model
tree_model=DecisionTreeClassifier(random_state=101)
tree_model.fit(X_train_scaled,y_train)

# Make predictions on the test set

scaler=StandardScaler()
X_train_s=scaler.fit_transform(X_train)
X_test_s=scaler.transform(X_test)
tree_model=DecisionTreeClassifier(random_state=101)
tree_model.fit(X_train_s,y_train)
tree_predictions=tree_model.predict(X_test_s)


# Evaluate the model

print("Decision tree")
print("Accuracy:",accuracy_score(y_test,tree_predictions))
print("Confusion Matrix:\n",confusion_matrix(y_test,tree_predictions))
print("Classification Report:\n",classification_report(y_test,tree_predictions))

Decision tree
Accuracy: 0.9210526315789473
Confusion Matrix:
 [[66  6]
 [ 3 39]]
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.92      0.94        72
           1       0.87      0.93      0.90        42

    accuracy                           0.92       114
   macro avg       0.91      0.92      0.92       114
weighted avg       0.92      0.92      0.92       114



#RANDOMFORESTCLASSIFIER


In [ ]:
from sklearn.ensemble import RandomForestClassifier
# INitialize and train random forest model

forest_model =RandomForestClassifier(n_estimators=150,random_state=101)
forest_model.fit(X_train_scaled,y_train)

# Make predictions on the test set
forest_predictions=forest_model.predict(X_test_scaled)

# Evaluate the model
print("Random Forest")
print("Accuracy:",accuracy_score(y_test,forest_predictions))
print("Confusion Matrix:\n",confusion_matrix(y_test,forest_predictions))
print("Classification Report:\n",classification_report(y_test,forest_predictions))

Random Forest
Accuracy: 0.9736842105263158
Confusion Matrix:
 [[71  1]
 [ 2 40]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.99      0.98        72
           1       0.98      0.95      0.96        42

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



# SVM (SUPPORT VECTOR MACHINE)


In [ ]:
from sklearn.svm import SVC
# initialize and train the SVM model

svm_model=SVC(kernel='linear',random_state=101)
svm_model.fit(X_train_scaled,y_train)
# make predictions on the test data

svm_predictions=svm_model.predict(X_test_scaled)
# evaluate the model

print("SVM")
print("Accuracy:",accuracy_score(y_test,svm_predictions))
print("Confusion Matrix:\n",confusion_matrix(y_test,svm_predictions))
print("Classification Report:\n",classification_report(y_test,svm_predictions))

SVM
Accuracy: 0.9824561403508771
Confusion Matrix:
 [[71  1]
 [ 1 41]]
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99        72
           1       0.98      0.98      0.98        42

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



#NAIVE BYES

In [ ]:
from sklearn.naive_bayes import GaussianNB

# Initialize and train the Naive Bayes model
nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)

# Make predictions on the test data
nb_predictions = nb_model.predict(X_test_scaled)

# Evaluate the model
print("Naive Bayes")
print("Accuracy:", accuracy_score(y_test, nb_predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, nb_predictions))
print("Classification Report:\n", classification_report(y_test, nb_predictions))

Naive Bayes
Accuracy: 0.9385964912280702
Confusion Matrix:
 [[68  4]
 [ 3 39]]
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.94      0.95        72
           1       0.91      0.93      0.92        42

    accuracy                           0.94       114
   macro avg       0.93      0.94      0.93       114
weighted avg       0.94      0.94      0.94       114



In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

# Define the parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [1, 0.1, 0.01, 0.001],
    'kernel': ['rbf']
}

# Initialize the SVM model
svm_model = SVC(random_state=101)

# Perform grid search
grid_search = GridSearchCV(svm_model, param_grid, refit=True, verbose=2)
grid_search.fit(X_train_scaled, y_train)

# Get the best parameters and estimator
print("Best Parameters:", grid_search.best_params_)
best_svm_model = grid_search.best_estimator_

# Make predictions on the test data
best_svm_predictions = best_svm_model.predict(X_test_scaled)

# Evaluate the model
print("Best SVM Accuracy:", accuracy_score(y_test, best_svm_predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, best_svm_predictions))
print("Classification Report:\n", classification_report(y_test, best_svm_predictions))

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=   0.0s
[CV] END ......................C=0.1, gamma=0.01

# CONCLUSIONS

Support Vector Machines (SVM) often achieve high accuracy .

1. -> Handles Complex Data: SVMs work well with high-dimensional data (many features) and can separate classes effectively.

2. -> Reduces Overfitting: By focusing on the best boundary (hyperplane) with maximum margin, SVMs avoid overfitting.

3. -> Kernel Trick: This allows SVMs to handle non-linear relationships by transforming data into higher dimensions.

4. -> Maximizes Margin: Ensures the boundary is far from data points, improving generalization to new data.

5. -> Regularization: Controls the balance between fitting the training data and keeping the model simple.
